# Generated by Django 3.2.22 on 2023-10-26 18:52

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('book_author', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reserved', models.BooleanField()),
                ('book_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='book_image')),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.IntegerField(max_length=10)),
                ('post_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
