# Generated by Django 3.2.22 on 2023-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpost',
            name='owner_phone',
            field=models.IntegerField(),
        ),
    ]
