# Generated by Django 3.2.22 on 2023-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0002_alter_bookpost_owner_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookpost',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='bookpost',
            name='owner_phone',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookpost',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
