# Generated by Django 3.2.22 on 2023-11-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0003_auto_20231029_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
