# Generated by Django 3.2.22 on 2023-11-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0004_alter_bookpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpost',
            name='condition',
            field=models.CharField(choices=[('as_new', 'As new'), ('fine', 'Fine'), ('v_good', 'Very Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=10),
        ),
    ]
