# Generated by Django 4.2.7 on 2023-11-19 10:22

import autoslug.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0005_alter_bookpost_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpost',
            name='condition',
            field=models.CharField(choices=[('as_new', 'As New'), ('fine', 'Fine'), ('v_good', 'Very Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bookpost',
            name='owner_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IE'),
        ),
        migrations.AlterField(
            model_name='bookpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='title', unique=True),
        ),
    ]
